/**
 * Helper to sanitize dynamic string inputs and prevent HTML injection in email templates.
 */
export const escapeHtml = (str) => {
  if (typeof str !== 'string') return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
};

export const renderMunicipalityEmailContent = (payload) => {
  const safeComplaintId = escapeHtml(payload.complaintId || '');
  const safeIssueType = escapeHtml(payload.issueType || 'OTHER');
  const safeSeverity = escapeHtml(payload.severity || 'MEDIUM');
  const safeConfidence = Math.round((payload.aiConfidence || 0) * 100);
  const safeAddress = escapeHtml(payload.address || 'Captured GPS Location');
  const safeMunName = escapeHtml(payload.municipalityName || 'Local Authority');
  const safeDescription = escapeHtml(payload.description || 'No description provided.');
  const safeLat = payload.latitude ? parseFloat(payload.latitude).toFixed(6) : '';
  const safeLon = payload.longitude ? parseFloat(payload.longitude).toFixed(6) : '';

  const subject = `New FixMyRoad Complaint — ${safeComplaintId}`;

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${subject}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0f172a; color: #f8fafc; margin: 0; padding: 20px; }
    .container { max-width: 600px; margin: 0 auto; background-color: #1e293b; border-radius: 12px; border: 1px solid #334155; padding: 30px; }
    .header { border-b: 1px solid #334155; padding-bottom: 20px; margin-bottom: 20px; }
    .badge { display: inline-block; padding: 4px 10px; border-radius: 6px; font-weight: bold; font-size: 12px; }
    .badge-critical { background-color: rgba(244, 63, 94, 0.2); color: #fb7185; border: 1px solid #f43f5e; }
    .badge-high { background-color: rgba(245, 158, 11, 0.2); color: #fbbf24; border: 1px solid #f59e0b; }
    .badge-medium { background-color: rgba(6, 182, 212, 0.2); color: #22d3ee; border: 1px solid #06b6d4; }
    .badge-low { background-color: rgba(16, 185, 129, 0.2); color: #34d399; border: 1px solid #10b981; }
    .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    .table td { padding: 10px; border-bottom: 1px solid #334155; font-size: 14px; }
    .table td.label { color: #94a3b8; font-weight: 600; width: 35%; }
    .table td.value { color: #ffffff; font-weight: 500; }
    .footer { margin-top: 25px; padding-top: 15px; border-top: 1px solid #334155; font-size: 12px; color: #64748b; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h2 style="color: #38bdf8; margin: 0 0 5px 0;">FixMyRoad Municipal Alert</h2>
      <p style="color: #94a3b8; margin: 0; font-size: 13px;">New Road Damage Complaint Assigned to ${safeMunName}</p>
    </div>

    <div style="background-color: #0f172a; padding: 15px; border-radius: 8px; margin-bottom: 20px; border: 1px solid #334155;">
      <span style="color: #94a3b8; font-size: 12px; font-weight: bold; text-transform: uppercase;">Official Complaint ID</span>
      <h1 style="color: #38bdf8; margin: 5px 0 0 0; font-family: monospace; font-size: 24px;">${safeComplaintId}</h1>
    </div>

    <table class="table">
      <tr>
        <td class="label">Issue Classification</td>
        <td class="value">${safeIssueType}</td>
      </tr>
      <tr>
        <td class="label">AI Confidence</td>
        <td class="value">${safeConfidence}%</td>
      </tr>
      <tr>
        <td class="label">Estimated Severity</td>
        <td class="value">
          <span class="badge badge-${safeSeverity.toLowerCase()}">${safeSeverity}</span>
        </td>
      </tr>
      <tr>
        <td class="label">GPS Location</td>
        <td class="value">${safeLat}, ${safeLon}</td>
      </tr>
      <tr>
        <td class="label">Street Address</td>
        <td class="value">${safeAddress}</td>
      </tr>
      <tr>
        <td class="label">Responsible Authority</td>
        <td class="value">${safeMunName}</td>
      </tr>
      <tr>
        <td class="label">Citizen Description</td>
        <td class="value"><em>"${safeDescription}"</em></td>
      </tr>
    </table>

    <p style="font-size: 13px; color: #cbd5e1;">
      Please log in to your FixMyRoad Municipality Dashboard to review defect details and process repairs.
    </p>

    <div class="footer">
      Automated civic notification generated by FixMyRoad Engine • Do not reply to this email directly.
    </div>
  </div>
</body>
</html>
  `;

  const text = `
FixMyRoad — New Road Damage Complaint Alert

Complaint ID: ${safeComplaintId}
Issue: ${safeIssueType}
Severity: ${safeSeverity}
AI Confidence: ${safeConfidence}%
Location: ${safeLat}, ${safeLon}
Address: ${safeAddress}
Municipality: ${safeMunName}
Description: ${safeDescription}

Please log in to the FixMyRoad Municipality Dashboard to review and process this complaint.
  `;

  return { subject, html, text };
};
